# Token Metrics Indexer
# Note: For hackathon, consider implementing this logic in backend
# by querying the DEX indexer GraphQL endpoint

name: IntelliQuant-TokenMetrics
description: Aggregates token health metrics from DEX data

# Minimal contract setup required by Envio (not actively used)
# Token metrics are calculated in backend by querying DEX indexer
contracts:
  - name: DummyContract
    handler: src/EventHandlers.ts
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"

networks:
  - id: 10143
    start_block: 0
    contracts:
      # Using real WMON contract address instead of zero address
      # Metrics calculated in backend via GraphQL queries
      - name: DummyContract
        address:
          - "0x760AfE86e5de5fa0Ee542fc7B7B713e1c5425701" # WMON token - minimal indexing
